jobs:
  build_release:
    name: build_release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: build
      run: "mvn clean package -DskipTests \necho \"artifactPath=$(pwd)/cli/target\"\
        \ >> $GITHUB_ENV\nversion=$(cat VERSION) \ntag=${GITHUB_REF_NAME}\necho \"\
        version=$version\" >> $GITHUB_ENV\necho \"tag=$tag\" >> $GITHUB_ENV\n"
    - continue-on-error: true
      run: echo version is ${{ env.version }}
    - continue-on-error: true
      run: echo tag is ${{ env.tag }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
      id: create_release
      name: release
      uses: actions/create-release@v1
      with:
        body: ${{ env.version }} auto-generated by github actions
        draft: true
        prerelease: false
        release_name: ${{ env.tag }}
        tag_name: ${{ env.tag }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
      name: upload release
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/java-archive
        asset_name: ysomap.jar
        asset_path: ${{ env.artifactPath }}/ysomap.jar
        upload_url: ${{ steps.create_release.outputs.upload_url }}
name: build-release
on:
  repository_dispatch:
    types: trigger-ga___github-action-build-and-release.yml
run-name: Auto Build And Release YSOMAP
